Clarify sub-millisecond precision is allowed
toml-lang/toml pull request #805
Opened 2021-01-23 22:58 UTC by aduh95

"Millisecond precision is required" could be interpreted as a requirement for input to be valid TOML. This commit adds examples of valid TOML time values that uses tens of second to remove the ambiguity.

Refs: https://github.com/alexcrichton/toml-rs/pull/416

2021-01-24 12:27 UTC, ChristianSi commented
I don't think this is necessary, but it certainly cannot hurt.

2021-02-28 13:40 UTC, bl-ue approved these changes
👌🏻

2021-03-02 00:19 UTC, eksortso approved these changes
LGTM

2022-11-12 00:58 UTC, eksortso commented
However, upon reflection, I think a little more explanation in the text is necessary. We currently state that "millisecond precision is required," but it's unclear that we are referring to the parsers' level of support for precision, not the users' precision, which should be arbitrary. Perhaps we ought to change the precision text to read as follows:

> Implementations should support at least millisecond precision. Additional digits of precision may be specified, but if they exceed the supported precision, then the extra digits must be _truncated_, not rounded.

Then, if it wouldn't be too much detail, we could indicate what the resulting values would look like by referring back to the examples, to make this crystal clear.

> For instance, a specified value of `00:32:00.999999` would be truncated to `00:32:00.999` when parsed with millisecond precision.

Thoughts?

2022-11-13 10:03 UTC, ChristianSi commented
I would write "must support" instead of "should support", otherwise this sounds good. But I would tend not to the include the truncation example – I think the spec is perfectly clear even without it.

Also keep in mind that we repeat this language three times (for each of the relevant date/time types), so brevity is important. I suppose you mean to include the truncation example just once. Sure, that would be possible, but I don't think it's necessary.

2022-11-14 03:30 UTC, eksortso commented
It was intended to be succinct; I wrote it knowing that it would be repeated. We don't need to show the truncation example, but I do insist that we put emphasis on the word _truncated_.

I didn't intend to relax the millisecond precision requirement, which I'm almost certain some implementations will do anyway. I was only trying to avoid saying "must" twice, and I forgot the phrases in [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119.html) that meant the same thing. We technically aren't using RFC 2119 now, but #870 may push us that way.

Let's return to the original wording somewhat for that first sentence.

> Implementations are required to support at least millisecond precision. Additional digits of precision may be specified, but if they exceed the supported precision, then the extra digits must be _truncated_, not rounded.

2022-11-14 21:20 UTC, eksortso requested changes
[toml.md](https://github.com/toml-lang/toml/files/10007017/toml.md)
Here are the changes to clarify that the sub-millisecond precision is a requirement specifically for the implementations to support.

2022-11-15 17:41 UTC, eksortso approved these changes
Thank you @aduh95 for including the changes.

2022-11-15 17:44 UTC, eksortso commented
@pradyunsg This PR draws an important distinction and relieves some potential confusion. What are your thoughts?

2022-11-16 10:03 UTC, ChristianSi approved these changes
LGMT!

2023-04-03 16:54 UTC, eksortso commented
@pradyunsg This has been sitting dormant for four months. Does anything more need done?

2023-06-16 16:16 UTC, eksortso commented
@pradyunsg It's been six months. What are your thoughts on this? [Can we merge it for v1.1.0?](https://github.com/toml-lang/toml/issues/928#issuecomment-1294659512)

2023-06-16 16:21 UTC, ChristianSi commented
Pleeeeese!

2025-03-17 16:42 UTC, merged