Hydrogen deuterium patch 1
toml-lang/toml pull request #819
Opened 2021-04-25 15:43 UTC by HydrogenDeuterium

改良让人迷惑的表述。改动两处尽管可能更加符合原文，但是对于中文母语者的阅读思维习惯并不合理。
我一开始也没有反应过来，品味了一会之后才理解其含义，并且认为改动后的版本更加容易让人理解。

2021-04-25 17:33 UTC, marzer requested changes
This PR radically alters the repository, so much so that I suspect you're targeting the wrong repo altogether. Did you mean to submit this PR against the repo you originally forked (https://github.com/LongTengDao/TOML)?

2021-04-25 19:02 UTC, pradyunsg commented
Hiya!

It's unclear what this PR is for. Could you please clarify?

2021-04-28 05:58 UTC, LongTengDao commented
@HydrogenDeuterium 虽然 LongTengDao/TOML 是从 toml-lang/toml fork 出的，但它并不是官方的汉化版（虽然现在的官方汉化版也是我翻译的，但两种翻译遵循的原则是不同的原则），它将作为一个独立的 repo 长期存在的。

你需要选定一下贡献对象：

1. 如果你要改进的是我的版本的 repo，请在 LongTengDao/TOML 而不是这里提交 pull request，并注意在选择目标仓库的步骤，确认提交仓库正确。
2. 如果你要改进的是官方汉化版，请移步 toml-lang/toml.io，并重新 fork、修改、pull request，官方国际化并不在主规范 repo 中。注意，官方汉化版中我的译文和 LongTengDao/TOML 中是不完全相同的，请确保你的修改是基于目标仓库，而不是直接把 LongTengDao/TOML 中的内容粘贴过去（那会造成海量的意外修改）。

感谢对 TOML 的关注与贡献！

2021-05-08 15:23 UTC, pradyunsg commented
Closing based on the above.

2021-05-08 15:23 UTC, closed without merging